version: '3.7'

services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: moodle-mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodleuser
      - MARIADB_PASSWORD=moodlepassword
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - moodle_network

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle-moodle
    restart: always
    depends_on:
      - mariadb
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_PASSWORD=moodlepassword
      - MOODLE_DATABASE_NAME=moodle
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - moodle_data:/bitnami/moodle
    networks:
      - moodle_network

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local

networks:
  moodle_network:
    driver: bridge
